<?php

// error_reporting(E_ALL);
// ini_set("display_errors", 1);
ini_set('session.cookie_httponly', 1);

return array(
    'URL' => (isset($_SERVER['HTTPS']) ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'] . str_replace('public', '', dirname($_SERVER['SCRIPT_NAME'])),
    'PATH_CONTROLLER' => realpath(dirname(__FILE__) . '/../../') . '/application/controller/',
    'PATH_VIEW' => realpath(dirname(__FILE__) . '/../../') . '/application/view/',
    'PATH_AVATARS' => realpath(dirname(__FILE__) . '/../../') . '/public/avatars/',
    'PATH_AVATARS_PUBLIC' => 'avatars/',
    'PATH_APP_MEDIA' => realpath(dirname(__FILE__) . '/../../') . '/public/img/apps/',
    'PATH_IMG_MEDIA' => realpath(dirname(__FILE__) . '/../../') . '/public/img/',
    'DEFAULT_CONTROLLER' => 'store',
    'DEFAULT_ACTION' => 'index',
    'DEFAULT_META_TITLE' => 'CourseSuite',
    'DEFAULT_META_KEYWORDS' => 'coursesuite, coursesuite ninja, lms, online learning, html5 scorm, scorm package, scorm author, interactive learning, document conversion, courseware, moodle',
    'DEFAULT_META_DESCRIPTION' => 'CourseSuite is a suite of online web apps allowing rapid creation of interactive and intuitive HTML5-based SCORM courses.',
    'DEFAULT_META_COPYRIGHT' => '&copy; <a href="http://www.coursesuite.ninja">CourseSuite</a> 2016-3016',
    'PATH_VIEW_PRECOMPILED' => realpath(dirname(__FILE__) . '/../../') . '/precompiled/',
    'DB_TYPE' => 'mysql',
    'DB_HOST' => '127.0.0.1',
    'DB_NAME' => 'cs_preprod',
    'DB_USER' => 'preprod',
    'DB_PASS' => 'RTX2VQ0}Ny',
    'DB_PORT' => '3306',
    'DB_CHARSET' => 'utf8',
    'CAPTCHA_WIDTH' => 359,
    'CAPTCHA_HEIGHT' => 100,

    'GOOGLE_CAPTCHA_SECRET' => '6LerkRcTAAAAAEUuS9ihNcY5m1cal1atUwl3iPTa',
    'GOOGLE_CAPTCHA_SITEKEY' => '6LerkRcTAAAAAE9yKd7WVCXGDlhhvN_MqGH7vwwe',

    'GOOGLE_INVISIBLE_CAPTCHA_SITEKEY' => '6LewIiYUAAAAAJcV-bQRfk824cYcsYwkIZ99Bpsy',
    'GOOGLE_INVISIBLE_CAPTCHA_SECRET' => '6LewIiYUAAAAAJUOJL7dg8ImX06LZ0iyMqqOPh2-',

    'GOOGLE_ANALYTICS_ID' => 'UA-68767047-1',
    'COOKIE_RUNTIME' => 1209600,
    'COOKIE_PATH' => '/',
    'COOKIE_DOMAIN' => "",
    'COOKIE_SECURE' => false,
    'COOKIE_HTTP' => true,
    'SESSION_RUNTIME' => 604800,
    'USE_GRAVATAR' => true,
    'GRAVATAR_DEFAULT_IMAGESET' => 'wavatar',
    'GRAVATAR_RATING' => 'pg',
    'AVATAR_SIZE' => 44,
    'AVATAR_JPEG_QUALITY' => 85,
    'AVATAR_DEFAULT_IMAGE' => 'default.jpg',
    'SLIDE_PREVIEW_WIDTH' => 400,
    'SLIDE_PREVIEW_HEIGHT' => 300,
    'SLIDE_THUMB_WIDTH' => 120,
    'SLIDE_THUMB_HEIGHT' => 90,
    'ENCRYPTION_KEY' => 'gQTwyP#HpXWS%5cWjMT#yUzT!UAN',
    'HMAC_SALT' => 'SP27uVe^zujNW9apqg#kaqA(BAx',

    'EMAIL_USED_MAILER' => 'phpmailer',
    'EMAIL_USE_SMTP' => false,
    'EMAIL_SMTP_HOST' => 'mail.coursesuite.com.au',
    'EMAIL_SMTP_AUTH' => true,
    'EMAIL_SMTP_USERNAME' => 'no.user', // 'no.user',
    'EMAIL_SMTP_PASSWORD' => 'iuh@943^f',
    'EMAIL_SMTP_PORT' => 465, // 587, // 465
    'EMAIL_SMTP_ENCRYPTION' => false, // 'tls', // 'ssl',

    'EMAIL_PASSWORD_RESET_URL' => 'login/verifypasswordreset',
    'EMAIL_PASSWORD_RESET_FROM_EMAIL' => 'no-reply@coursesuite.ninja',
    'EMAIL_PASSWORD_RESET_FROM_NAME' => 'My Coursesuite',
    'EMAIL_PASSWORD_RESET_SUBJECT' => 'Password reset for CourseSuite',
    'EMAIL_VERIFICATION_URL' => 'register/verify',
    'EMAIL_VERIFICATION_FROM_EMAIL' => 'no-reply@coursesuite.ninja',
    'EMAIL_VERIFICATION_FROM_NAME' => 'CourseSuite',
    'EMAIL_VERIFICATION_SUBJECT' => 'Account activation for CourseSuite',
    'EMAIL_ADMIN' => 'admin@coursesuite.ninja',
    'EMAIL_SUBSCRIPTION' => 'info@coursesuite.com.au',
    'EMAIL_STANDARD_FROM_NAME' => 'CourseSuite Notifications',
    'EMAIL_STANDARD_FROM_ADDR' => 'info@coursesuite.com.au',
    'EMAIL_STANDARD_NO_REPLY' => 'no-reply@coursesuite.ninja',
    'DIGEST_USERS' => array(
        'admin' => 'nT5YyYb233WB',
        'apiuser' => 'rpxC5kCmYuFn',
        'tokenuser' => 'GEv6mJ7wJgWR',
        'fastspring' => 'e93NcNdpntFq',
        'discourse' => '3kurpzSGRAq4',
        'apimatrix' => 'f56jPFGo85fs6',
        'apianmf' => 'xGincUfPNB93L',
        'apikaplan' => 'VCIg3OgyUM658e'
    ),
    'DISCOURSE_SSO_SECRET' => 'supersecretkeythatnoonewilleverknow',
    'CLOUDCONVERT_API_KEY' => '8pxT0DHRE5lpcVzildrPoEbztL9rc5Es89xG0incUfPNB93LLZueEr7zTK7PTuZmcV1hXkRMITbhjS-U1NnnzQ',
    'FASTSPRING_SECRET_KEY' => '263c9f8ead6933f5794bf79dc19e48fc',
    'FASTSPRING_PARAM_APPEND' => '',
    'FASTSPRING_STORE' => 'coursesuite',
    'FASTSPRING_API_USER' => 'admin@coursesuite.ninja',
    'FASTSPRING_API_PASSWORD' => 'I9AN2on42Tom',
    'STORE_INFO_SHOW_PRICING' => true,
    'GLOBAL_FOOTER_COLUMN_1' => '<h3>About Us</h3><p>We are a small Australian team focused on developing a suite of great online web apps that allow rapid creation of interactive and intuitive HTML5-based SCORM courses. We also release Open Source plugins for Moodle, and produce online course content.</p>',
    'GLOBAL_FOOTER_COLUMN_2' => '<h3>More information</h3><p><a href="/content/privacy">Privacy</a> <a href="http://forum.coursesuite.ninja/categories/">Forum</a> <a href="http://sites.fastspring.com/coursesuite/order/contact">Contact Us</a> <a href="http://avide.com.au/">Avide eLearning</a></p>',
    'GLOBAL_FOOTER_COLUMN_3' => '<h3>all rights reserved</h3><p>&copy; CourseSuite 2016-3016<br/><a href="mailto:&#105;&#110;&#102;&#111;&#64;&#99;&#111;&#117;&#114;&#115;&#101;&#115;&#117;&#105;&#116;&#101;&#46;&#99;&#111;&#109;&#46;&#97;&#117;">&#105;&#110;&#102;&#111;&#64;&#99;&#111;&#117;&#114;&#115;&#101;&#115;&#117;&#105;&#116;&#101;&#46;&#99;&#111;&#109;&#46;&#97;&#117;</a></p>',
    'MAILCHIMP_API_KEY' => '0803286b6f9c681c80d7ad751d6beec3-us11',
    'MAILCHIMP_LIST_ID' => '08344979e7',
    'MAILCHIMP_INTEREST_ID' => 'd3a65e22a1',
    'FORCE_HANDLEBARS_COMPILATION' => false, // set to true to force recompilation of handlebars templates on the fly

    'ADMIN_ACCOUNT_LEVEL' => 7,
    'ADMIN_ACCOUNT_EMAIL' => '%@coursesuite.com.au',
);
